import React from 'react';
import { AnalysisResults } from '../types';
import {
  Printer,
  Download,
  Brain,
  CheckCircle2,
  ShieldAlert,
  AlertTriangle,
  FileText,
  BarChart2,
  Database,
  Target
} from 'lucide-react';

interface ReportProps {
  analysis: AnalysisResults;
  onNavigate: (tab: string) => void;
}

export const ReportView: React.FC<ReportProps> = ({ analysis, onNavigate }) => {
  const { overallScore, overallStatus, profile, targetAnalysis, leakageFindings, risks, recommendations, aiSummary } = analysis;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="p-6 max-w-5xl mx-auto space-y-8 text-slate-900 dark:text-slate-100 print:bg-white print:text-black print:p-0">
      {/* Print Controls (Hidden when printing) */}
      <div className="flex items-center justify-between border-b border-slate-800 pb-4 print:hidden">
        <div>
          <span className="text-xs font-semibold text-indigo-400 uppercase tracking-wider">
            Exportable Audit Document
          </span>
          <h1 className="text-2xl font-extrabold text-white">
            ML Data-Readiness Report
          </h1>
        </div>

        <button
          onClick={handlePrint}
          className="px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl font-bold text-xs flex items-center space-x-2 shadow-lg transition-all"
        >
          <Printer className="w-4 h-4" />
          <span>Print / Export as PDF</span>
        </button>
      </div>

      {/* Printable Document Container */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-8 space-y-8 shadow-2xl print:bg-white print:text-slate-900 print:border-none print:shadow-none">
        {/* Document Header */}
        <div className="flex justify-between items-start border-b border-slate-800 print:border-slate-300 pb-6">
          <div>
            <div className="flex items-center space-x-2">
              <Brain className="w-7 h-7 text-indigo-400 print:text-indigo-600" />
              <h2 className="text-2xl font-black tracking-tight text-white print:text-slate-900">
                ML Data-Readiness Report
              </h2>
            </div>
            <p className="text-xs text-slate-400 print:text-slate-600 mt-1">
              Generated by ML Data-Readiness Risk Analyzer on {new Date(analysis.createdAt).toLocaleDateString()}
            </p>
          </div>

          <div className="text-right">
            <div className="text-3xl font-black text-white print:text-slate-900">
              {overallScore} / 100
            </div>
            <div className="mt-1">
              {overallStatus === 'Ready' && (
                <span className="px-3 py-1 rounded-full text-xs font-bold bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 print:bg-emerald-100 print:text-emerald-800">
                  🟢 READY
                </span>
              )}
              {overallStatus === 'Needs Review' && (
                <span className="px-3 py-1 rounded-full text-xs font-bold bg-amber-500/20 text-amber-400 border border-amber-500/30 print:bg-amber-100 print:text-amber-800">
                  🟡 NEEDS REVIEW
                </span>
              )}
              {overallStatus === 'High Risk' && (
                <span className="px-3 py-1 rounded-full text-xs font-bold bg-rose-500/20 text-rose-400 border border-rose-500/30 print:bg-rose-100 print:text-rose-800">
                  🔴 HIGH RISK
                </span>
              )}
            </div>
          </div>
        </div>

        {/* Section 1: Dataset Information & Objective */}
        <div className="space-y-3">
          <h3 className="text-sm font-bold uppercase tracking-wider text-indigo-400 print:text-indigo-700">
            1. Dataset Profile & ML Objective
          </h3>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 bg-slate-950 print:bg-slate-100 p-4 rounded-xl border border-slate-800 print:border-slate-300 text-xs">
            <div>
              <span className="text-slate-500 print:text-slate-600 font-medium">Dataset Name</span>
              <p className="font-bold text-white print:text-slate-900 truncate">{analysis.datasetName}</p>
            </div>
            <div>
              <span className="text-slate-500 print:text-slate-600 font-medium">Prediction Type</span>
              <p className="font-bold text-white print:text-slate-900 capitalize">{analysis.predictionType}</p>
            </div>
            <div>
              <span className="text-slate-500 print:text-slate-600 font-medium">Target Column</span>
              <p className="font-bold text-indigo-400 print:text-indigo-700">{analysis.targetColumn}</p>
            </div>
            <div>
              <span className="text-slate-500 print:text-slate-600 font-medium">Total Rows / Cols</span>
              <p className="font-bold text-white print:text-slate-900">{profile.rowCount.toLocaleString()} × {profile.columnCount}</p>
            </div>
          </div>
        </div>

        {/* Section 2: AI Executive Summary */}
        {aiSummary && (
          <div className="space-y-3">
            <h3 className="text-sm font-bold uppercase tracking-wider text-indigo-400 print:text-indigo-700">
              2. Executive AI Assessment
            </h3>
            <div className="bg-slate-950 print:bg-slate-50 p-4 rounded-xl border border-slate-800 print:border-slate-300 text-xs text-slate-300 print:text-slate-800 leading-relaxed font-medium">
              {aiSummary.plainLanguageSummary}
            </div>
          </div>
        )}

        {/* Section 3: Critical Risks & Leakage */}
        <div className="space-y-3">
          <h3 className="text-sm font-bold uppercase tracking-wider text-indigo-400 print:text-indigo-700">
            3. Data Leakage & Critical ML Risks
          </h3>
          {risks.length === 0 ? (
            <p className="text-xs text-emerald-400">No critical data leakage or severe ML risks detected.</p>
          ) : (
            <div className="space-y-2">
              {risks.map((r, idx) => (
                <div key={idx} className="bg-slate-950 print:bg-slate-50 p-3 rounded-xl border border-slate-800 print:border-slate-300 text-xs space-y-1">
                  <div className="flex items-center space-x-2 font-bold text-white print:text-slate-900">
                    <span className="text-rose-400 print:text-rose-600">[{r.severity.toUpperCase()}]</span>
                    <span>{r.title}</span>
                  </div>
                  <p className="text-slate-400 print:text-slate-700">{r.evidence}</p>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Section 4: Prioritized Recommendations */}
        <div className="space-y-3">
          <h3 className="text-sm font-bold uppercase tracking-wider text-indigo-400 print:text-indigo-700">
            4. Pre-Training Action Plan
          </h3>
          <div className="space-y-2">
            {recommendations.map((rec, idx) => (
              <div key={idx} className="bg-slate-950 print:bg-slate-50 p-3 rounded-xl border border-slate-800 print:border-slate-300 text-xs flex items-start space-x-3">
                <span className="font-bold text-indigo-400 print:text-indigo-700">P{rec.priority}.</span>
                <div>
                  <p className="font-bold text-white print:text-slate-900">{rec.title}</p>
                  <p className="text-slate-300 print:text-slate-800 mt-0.5">{rec.recommendedAction}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Section 5: Final Decision */}
        <div className="pt-4 border-t border-slate-800 print:border-slate-300 flex justify-between items-center text-xs">
          <div>
            <span className="font-bold text-slate-400 print:text-slate-600">Final Decision:</span>{' '}
            <strong className="text-white print:text-slate-900 uppercase font-extrabold">{overallStatus}</strong>
          </div>
          <span className="text-slate-500">Audited by ML Readiness Risk Analyzer</span>
        </div>
      </div>
    </div>
  );
};
